networks:
  app-network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    # Expose port 8000 (Gunicorn's port)
    expose:
      - '8000'
    env_file:
      - .env
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    # Map host port 5001 to Nginx's port 80
    ports:
      - '0.0.0.0:5001:80'
    networks:
      - app-network
    volumes:
      # Mount Nginx config
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app